#!/bin/bash

# System iOS Monitor - Hızlı Başlangıç Kılavuzu

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   📱 SYSTEM iOS MONITOR - HIZLI BAŞLANGIÇ KTILAVUZU      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "1️⃣  UBUNTU'DA BACKEND'İ BAŞLAT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd /home/snnunvr/Desktop/system_ios_monitor"
echo "  ./start_backend.sh"
echo ""
echo "  ✅ Backend 1571 portunda çalışacak"
echo "  ✅ API: http://localhost:1571"
echo "  ✅ Docs: http://localhost:1571/docs"
echo ""

echo "2️⃣  UBUNTU'DA FLUTTER'I ÇALIŞTI (OPSİYONEL - TEST İÇİN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # Başka bir terminal aç"
echo "  cd /home/snnunvr/Desktop/system_ios_monitor"
echo "  flutter run -d linux  # Linux Desktop"
echo ""

echo "3️⃣  IPHONE'DA TAILSCALE AYARLA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  a) App Store'dan 'Tailscale' uygulamasını indir"
echo "  b) İPhone: Tailscale ↓ → Connect → Sign in"
echo "  c) Ubuntu: Terminal aç"
echo "     $ sudo tailscale up"
echo "     → Linki browser'da aç ve authenticate et"
echo ""

echo "4️⃣  UBUNTU'NUN TAILSCALE IP'SİNİ ÖĞREN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ tailscale status"
echo ""
echo "  Çıktıda: ubuntu/100.x.x.x (Ubuntu IP adresi)"
echo "  👉 100.x.x.x kısmını kopyala"
echo ""

echo "5️⃣  IPHONE'DA FLUTTER UYGULAMASINI DEPLOY ET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # Xcode'u aç ve iOS ayarlarını yapılandır:"
echo "  open ios/Runner.xcworkspace"
echo ""
echo "  # Veya doğrudan cihaza deploy et:"
echo "  flutter run -d ios"
echo ""

echo "6️⃣  FLUTTER AYARLARINI YAPILANDIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  App açılırsa:"
echo "  1. Sağ alt köşedeki ⚙️ ikonuna tıkla"
echo "  2. 'Sunucu Ayarları' bölümüne git"
echo "  3. URL kısmına yaz: http://100.x.x.x:1571"
echo "     (100.x.x.x yerine Ubuntu Tailscale IP'sini koy)"
echo "  4. 'Test Bağlantı' butonuna tıkla"
echo "  5. Yeşil ✅ çıkmazsa URL'yi kontrol et"
echo ""

echo "7️⃣  UYGULAMAYA BAŞLA!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Şimdi iPhone'da gerçek zamanlı izleyebilirsin:"
echo "  📊 Dashboard - Sistem özeti"
echo "  🎮 GPU Monitor - GPU detayları"
echo "  🔌 Portlar - Açık portlar ve güvenlik"
echo "  🚀 Training - AI model training job'ları"
echo "  ⚡ Enerji - Aylık maliyet hesabı"
echo ""

echo "🆘 SORUN GIDERME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Backend bağlanmıyor:"
echo "   - Ubuntu'da backend çalışıyor mu? (./start_backend.sh)"
echo "   - Port açık mı? (curl http://localhost:1571/)"
echo "   - İPhone'da URL doğru mu?"
echo ""
echo "❌ GPU görmüyor:"
echo "   - NVIDIA kurulu mu? (nvidia-smi)"
echo "   - Sürücü güncel mi?"
echo ""
echo "❌ Flutter derlenmiyor:"
echo "   - flutter pub get çalıştır"
echo "   - flutter clean çalıştır"
echo ""

echo "📚 KAYNAK KÖDLERİ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Backend: backend/main.py"
echo "  Frontend: lib/main.dart"
echo "  Tema: lib/theme/app_theme.dart"
echo "  API Client: lib/services/api_client.dart"
echo ""
echo "  Monitoring Modülleri:"
echo "  • backend/monitors/gpu_monitor.py"
echo "  • backend/monitors/energy_monitor.py"
echo "  • backend/monitors/port_analyzer.py"
echo "  • backend/monitors/training_tracker.py"
echo ""

echo "📞 DESTEK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  README.md - Detaylı açıklamalar"
echo "  PROJECT_SUMMARY.md - Proje özeti"
echo "  start_backend.sh - Backend başlangıç scripti"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║              ✅ BAŞLAMAYA HAZIR!                          ║"
echo "║          Created with ❤️  for System Monitoring          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
