# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}


def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(__dir__, 'Flutter', 'flutter_export_environment.sh'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated Xcode build settings file not found: #{generated_xcode_build_settings_path}."
  end
  File.read(generated_xcode_build_settings_path).each_line do |line|
    match = line.match(/FLUTTER_ROOT=(.*)/)
    return match[1].strip.gsub('"', '') if match
  end
  raise 'FLUTTER_ROOT not found in flutter_export_environment.sh'
end

flutter_tools = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')
require File.expand_path(flutter_tools)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
